WebStore.UI/ViewComponents/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebStore.Application.Cart;

namespace WebStore.UI.ViewComponents
{
    public class CartViewComponent : ViewComponent
    {
        private readonly GetCart _getCart;
        public CartViewComponent(GetCart getCart)
        {
            _getCart = getCart;
        }
        public IViewComponentResult Invoke(string view = "Default")
        {
            if(view == "Small")
            {
                var totalValue = _getCart.Action().Sum(x => x.Value*x.Qty);
                return View(view, $"${totalValue}");
            }
            return View(view, _getCart.Action());
        }
    }
}

WebStore.UI/ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Application.Products;

namespace WebStore.UI.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private readonly GetCategoryMenu _getCategoryMenu;
        public CategoryMenuViewComponent(GetCategoryMenu getCategoryMenu)
        {
            _getCategoryMenu = getCategoryMenu;
        }
        public IViewComponentResult Invoke(string view = "Default")
        {
            return View(view, _getCategoryMenu.Action());
        }
    }
}

WebStore.UI/Pages/Shared/_CartPartial.cshtml
@model IEnumerable<WebStore.Application.Cart.GetCart.Response>
@{ 
    var base_path = Context.Request.PathBase;
}

<div id="main-cart" class="columns is-multiline">
    <div class="column is-12">
        <h2 class="title">Cart</h2>
        @foreach (var product in Model)
        {
            string lineValue = $"{product.Value * product.Qty}";
            var logo_image_path = $"{base_path}/ProductLogoImage/{product.ProductImage}";
            <article class="media">
                <figure class="media-left">
                    <p class="image is-64x64">
                        <img src="@logo_image_path" alt="Example image" />
                    </p>
                </figure>
                <div class="media-content">
                    <p class="title">@product.Name</p>
                    <div class="level">
                        <div class="level-item">@product.StockId</div>
                        <div class="level-item">@product.StockName</div>
                        <div class="level-item">
                            <div class="columns is-mobile">
                                <div class="column">
                                    <button class="button is-small is-primary"
                                            type="button"
                                            onclick="minusOneFromCart(event)"
                                            data-stock-id="@product.StockId">
                                        -
                                    </button>
                                </div>
                                <div class="column is-align-self-center" id="stock-qty-@(product.StockId)">
                                    @product.Qty
                                </div>
                                <div class="column">
                                    <button class="button is-small is-primary"
                                            type="button"
                                            onclick="addOneToCart(event)"
                                            data-stock-id="@product.StockId">
                                        +
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="level-item">$@product.Value</div>
                        <div class="level-item">$@lineValue</div>
                        <div class="level-item">
                            <a class="has-text-danger"
                               onclick="removeAllFromCart(event)"
                               data-stock-id="@product.StockId">Remove</a>
                        </div>
                    </div>
                </div>

            </article>

        }
    </div>
    <div class="column is-12">
        <div class="has-text-right">
            <a class="button is-success is-outlined" asp-page="/AllProducts">Continue Shopping</a>
            @if (Model.Count() > 0)
            {
                <a class="button is-success" asp-page="/Checkout/CustomerInfo">Go to Checkout</a>
            }
            else
            {
                <a class="button is-success" asp-page="/Checkout/CustomerInfo" disabled>Go to Checkout</a>
            }

        </div>
    </div>
</div>

WebStore.UI/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] : Demo Web Store UI by germistry</title>
    <link rel="icon" type="image/x-icon" href="~/images/squareLogo.png" />
    <environment include="Development">
        <link href="~/lib/bulma-0.9.1/bulma/css/bulma.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment include="Production">
        <link href="~/lib/bulma-0.9.1/bulma/css/bulma.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://kit.fontawesome.com/7f105cc73c.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item">
                <img src="~/images/BrandLogo.png" width="130" height="28">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" asp-page="/Index">Home</a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Products</a>
                    <vc:category-menu view="Default"></vc:category-menu>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">More</a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item">About</a>
                        <a class="navbar-item">Contact</a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" asp-page="/Privacy">Privacy</a>
                    </div>
                </div>
            </div>
            <div class="navbar-end">
                <vc:cart view="Small"></vc:cart>
                <div class="navbar-item">

                    <div class="buttons">

                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a class="button is-primary" asp-area="" asp-page="/Admin/Index">
                                    <span class="icon"><i class="fas fa-tools"></i></span>
                                    <span>Admin Panel</span>
                                </a>
                                <a class="button is-light" asp-controller="Account" asp-action="LogOut">
                                    <span class="icon"><i class="fas fa-sign-out-alt"></i></span>    
                                    <span>Sign Out</span>
                                </a>
                            }
                        }
                        else
                        {
                            <a class="button is-primary" asp-area="" asp-page="/Accounts/Login">
                                <span class="icon"><i class="fas fa-user"></i></span>
                                <span><strong>Sign In</strong></span>
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />

    @RenderBody()

    <footer class="footer">
        <div class="content has-text-centered">
            <p>
                <strong>WebStoreDemo</strong> by <a href="https://germistry.com">Krystal Ruwoldt</a>. The source code is licensed
                <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
                is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
            </p>
            <p>Product images a from <a href="https://pixabay.com">pixabay.com.</a></p>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment include="Production">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>